import { routing } from '../../i18n/routing'
import { site } from '../../config/site'

/** Join a path onto the canonical origin. `absoluteUrl('/en')` -> 'https://…/en'. */
export function absoluteUrl(path = '') {
  if (!path) return site.url
  return `${site.url}${path.startsWith('/') ? path : `/${path}`}`
}

/** The locale-prefixed pathname for a route slug. `('en', '')` -> '/en'. */
export function localePath(locale, slug) {
  return slug ? `/${locale}/${slug}` : `/${locale}`
}

/**
 * hreflang map for one slug across every configured locale, plus x-default.
 * Generated by looping `routing.locales`, so adding a language automatically
 * adds it to every page's alternates without touching any page file.
 */
export function buildHreflangMap(slug) {
  const languages = {}
  for (const locale of routing.locales) {
    languages[locale] = absoluteUrl(localePath(locale, slug))
  }
  languages['x-default'] = absoluteUrl(localePath(routing.defaultLocale, slug))
  return languages
}

/** Pick the SEO block for a locale, falling back to the default locale. */
export function seoFor(route, locale) {
  return route.seo[locale] || route.seo[routing.defaultLocale]
}

/**
 * Turn one `ROUTES` entry into a complete Next.js metadata object:
 * title, description, keywords, canonical, hreflang alternates, Open Graph
 * and Twitter Card. Replaces the old client-side `<SEO>` useEffect, which
 * only ran after JavaScript executed and emitted an identical canonical for
 * all fourteen converter routes.
 */
export function buildPageMetadata({ route, locale }) {
  const seo = seoFor(route, locale)
  const url = absoluteUrl(localePath(locale, route.slug))
  // Generated per locale by src/app/[locale]/opengraph-image.js.
  const images = [
    {
      url: absoluteUrl(`${localePath(locale, '')}${site.ogImagePath}`),
      width: 1200,
      height: 630,
      alt: seo.title,
    },
  ]

  return {
    title: seo.title,
    description: seo.description,
    keywords: seo.keywords,
    alternates: {
      canonical: url,
      languages: buildHreflangMap(route.slug),
    },
    openGraph: {
      type: 'website',
      siteName: site.siteName,
      title: seo.title,
      description: seo.description,
      url,
      locale,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      site: site.twitter,
      title: seo.title,
      description: seo.description,
      images,
    },
  }
}
