/**
 * Site-wide constants: canonical origin, brand names, contact + social handles.
 * Anything that appears in more than one page's metadata or JSON-LD lives here.
 */
export const site = {
  /** Canonical production origin — no trailing slash. */
  url: process.env.NEXT_PUBLIC_SITE_URL || 'https://imagecompressor.cloud',

  /** Human-facing brand name (Organization / SoftwareApplication name). */
  name: 'ImageCompress Cloud',

  /** og:site_name — matches what the old SEO component emitted. */
  siteName: 'ImageCompressor.cloud',

  /** Site-wide fallback description (root layout / WebSite schema). */
  description:
    'Free online image compressor and PDF toolkit. Compress images and PDFs to exact target sizes, convert documents, merge and split PDFs — 100% in your browser.',

  themeColor: '#10b981',

  /** Relative path to the social share image (generated by app/[locale]/opengraph-image.js). */
  ogImagePath: '/opengraph-image',

  twitter: '@imagecompressor',

  contactEmail: 'support@imagecompressor.cloud',
  privacyEmail: 'privacy@imagecompressor.cloud',

  /** Same-origin social/profile links used by Organization schema. */
  sameAs: [],
}
